# -*- coding: utf-8 -*-
"""bt_pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P1_2pidiFXJnzPAfpQqNX1U-0I9m69aH
"""

import pandas as pd

df = pd.read_csv('test.csv')
df

#Show 3 firts the rows
df.head(3)

#Show 3 end the rows
df.tail(3)

#Show random 3 the rows
df.sample(3)

#Show the columns and the rows
df.shape

#Show information
df.info()

#Show all the row index
df.index

#Show all the columns index
df.columns

#Set index
df.set_index('HoTen')
df.head()

#Set index nayf ghi đè bảng
df.set_index('HoTen', inplace=True)
df.head()

df.reset_index(inplace=True)
df.head()

#Lọc dữ liệu dòng cột index
df.loc[1]

#Lọc dữ liệu dòng cột index ([1, 2] đang dưới dạng list nên thêm 1 dâuys )
df.loc[[1, 2]]

#Lọc dữ liệu dòng cột index
df.loc[[1, 2], ['NgaySinh', 'PhongBan']]

df.loc[2:4, ['ID','ChucVu']]

df.head()

df.iloc[2, 1]

# Đếm số lượng danh mục lặp lại
df[['Luong', 'HoTen']].value_counts()
# Mảng tên các danh mục
#df['Luong'].unique()
# Số lượng danh mục
#df['Luong'].value_counts()

#Đếm số lượng giá trị thiếu trong mỗi cột
df.isnull().sum()

#Thay the gia tri thieu bang mot gia tri cu the
df.fillna(1, inplace=True)

#Xóa hàng bj trùng
df.drop_duplicates()

# Đổi tên cột
df.rename(columns={'ID':'IDNV'}, inplace=True)
df.head()

#Show data có điều kiện
df[df['Luong'] > 1500]

#Sắp xếp dữ liệu
df.sort_values('Luong', ascending=True)

#Sort index
df.sort_index()

#Gom nhom sau do thuc hien phep tinh -> tra ve dataFrame
df.groupby('PhongBan')['Luong'].mean()